"""Initial migration

Revision ID: 2727ad6c6067
Revises: 
Create Date: 2025-01-10 23:04:48.100161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2727ad6c6067'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('last_name', sa.String(length=15), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('license_number', sa.String(length=4), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_purchased', sa.DateTime(), nullable=False),
    sa.Column('wear', sa.Integer(), nullable=False),
    sa.Column('id_archer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_archer'], ['archers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('tip_weight', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('hard', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('data_purchased', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('wear', sa.Integer(), nullable=True),
    sa.Column('id_archer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_archer'], ['archers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('series', sa.JSON(), nullable=False),
    sa.Column('archer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['archer_id'], ['archers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity_of_shots', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('archer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['archer_id'], ['archers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainings')
    op.drop_table('tournaments')
    op.drop_table('shots')
    op.drop_table('chords')
    op.drop_table('archers')
    op.drop_table('trainers')
    op.drop_table('clubs')
    # ### end Alembic commands ###
